### ISSUE TITLE
Scaffold new React Native application

### ISSUE THREAD

**Issue by sainapsisSanvego** [Sainapsis/sainapsis-front-end-take-home#2]
- Rename `mobile-chat` to `old-mobile-chat`
- Create a `chat-components` directory
- Integrate [unistyles](https://reactnativeunistyles.vercel.app/start/introduction/)

**Comment by derwin-sainapsis** [comment]
Estaba viendo la documentación de unistyles y dicen que no tienen soporte para Expo go. Es decir, tendriamos que trabajar con una build de desarrollo de expo y cada vez que queramos compilar estilos, tenemos que hacer un prebuild de la aplicacion, cosa que me parece bastante tediosa.

Algo en especial por el cual se quiera integrar esta libreria?
Si mal no recuerdo, habiamos quedado en integrar NativeWind para el tema de estilos.
